### ISSUE TITLE
Coordinates and dimensions of addCube are switched

### ISSUE THREAD

**Issue by filipejsbrandao** [EmilPoulsen/AecHackBlazor#7]
I started playing with hackuble this morning. I read through the Geometry code to understand the inputs of Cube and addCube functions in C#. I would expect that the first three inputs (named x,y,z) would be the position coordinates of the cube (perhaps the center although this is not specified in the code). And the inputs named width, depth, height to be the dimensions of the cube. Yet the reverse is happening. Having a look at the JS code that adds the sphere to the context it is clear that x,y,z are being used to create the geometry and width, depth, height as the position coordinates.

**Comment by pm-Architect** [comment]
Hi @filipejsbrandao 
Great to see that you've already started playing around with hackuble!
The C# functions you're referring to are supposed to be direct reflections of Three.js functions in C#. Since this was a hackathon project, to begin with, we only added a few such functions, which might also be a bit buggy.
Thanks for pointing this out! We'll remember to fix this when we do a pass on the three.js functions.

**Comment by filipejsbrandao** [comment]
Hello @pm-Architect 
It is very good work for a hackaton, congrats to you and the rest of the team! 
I've also experimented adding one more input type, a boolean input. It seems fairly straightforward to expand the functionality of Hackuble. A feature I would love to see, but don't have the faintest idea where to start, is the ability to click on geometry in the viewport to edit the inputs. Best

**Comment by pm-Architect** [comment]
Thanks! Glad you like it!
That's an interesting idea. We're currently working on creating a version of hackuble for desktop, which will feature a visual scripting environment ;-)

**Comment by EmilPoulsen** [comment]
Thanks for the comment @filipejsbrandao. Don't be shy if you want to submit a pull request with a bug fix! 🙏
